# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-01-24 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sourceType', models.CharField(max_length=30, unique=True)),
                ('parsingModule', models.CharField(max_length=64)),
                ('parserClass', models.CharField(max_length=64)),
            ],
        ),
    ]
