# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-05-24 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaignfiles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sourcetype',
            old_name='parsingModule',
            new_name='module',
        ),
    ]
